title: Fiches Perso Shadowrun
description: Générateur de fiches de personnage pour Shadowrun 4ème édition
baseurl: "/"
url: "http://localhost:4000"
markdown: kramdown

# Déclaration de la collection
collections:
  characters:
    output: true
    permalink: /characters/:name/

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
