title: Fiches Perso Shadowrun
description: Générateur de fiches de personnage pour Shadowrun 4ème édition
baseurl: "/"
url: "https://guillaume-philippon.github.io"
markdown: kramdown

# Déclaration de la collection
collections:
  characters:
    output: true
    permalink: /characters/:name/
  contacts:
    output: true
    permalink: /contacts/:name/

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
